// Generated by lgx.guru. AI-authored tests are appended below the
// smoke test. The build pipeline runs these after the main module
// build; failures feed back to the AI for retry.
#include <logos_test.h>
#include "../src/hello_module_impl.h"

// Smoke test — proves the impl class can be constructed and destroyed
// without crashing. Always passes for a well-formed module.
LOGOS_TEST(hello_module_constructs) {
    HelloModuleImpl impl;
    (void)impl;
    LOGOS_ASSERT_TRUE(true);
}

// Test that getMessage returns 'hello'.
LOGOS_TEST(test_get_message) {
    HelloModuleImpl impl;
    LOGOS_ASSERT_EQ(impl.getMessage(), std::string("hello"));
}
